# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maxime van der Heijden
tagline:          'Personal Site'
description:      ''
url:              https://maximevdheijden.github.io//

highlighter:      rouge
markdown:         kramdown

paginate:         5

github:
  repo:           https://github.com/MaximevdHeijden/MaximevdHeijden.github.io
